apiVersion: v1
kind: Secret
metadata:
  name: {{ include "broker-client.fullname" . }}
  labels:
    {{- include "broker-client.labels" . | nindent 4 }}
type: Opaque
stringData:
  CLIENT_SECRET: {{ .Values.config.clientSecret | required "config.clientSecret is required" | quote }}
  ALLOWED_INTERNAL_SUBNETS: {{ .Values.config.allowedInternalSubnets | quote }}
  {{- if .Values.config.dnsServers }}
  DNS_SERVERS: {{ .Values.config.dnsServers | quote }}
  {{- end }}
  {{- if .Values.config.httpProxy }}
  HTTP_PROXY: {{ .Values.config.httpProxy | quote }}
  {{- end }}
  {{- if .Values.config.httpsProxy }}
  HTTPS_PROXY: {{ .Values.config.httpsProxy | quote }}
  {{- end }}
  {{- if .Values.config.allProxy }}
  ALL_PROXY: {{ .Values.config.allProxy | quote }}
  {{- end }}
  {{- if .Values.config.customCaBundleContent }}
  NODE_EXTRA_CA_CERTS: "/certs/custom-ca.crt"
  {{- end }}
{{- if .Values.config.customCaBundleContent }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "broker-client.fullname" . }}-ca-bundle
  labels:
    {{- include "broker-client.labels" . | nindent 4 }}
type: Opaque
data:
  custom-ca.crt: {{ .Values.config.customCaBundleContent | b64enc }}
{{- end }}
