{{- if and .Values.sbomCollector.enabled (eq .Values.sbomCollector.runAsDaemonSet true) }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "sbom-collector.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sbom-collector.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "sbom-collector.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/agent/secret.yaml") . | sha256sum }}
        {{- with .Values.sbomCollector.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        aikido-security: kubernetes-sbom-collector
        {{- include "sbom-collector.selectorLabels" . | nindent 8 }}
        {{- with .Values.sbomCollector.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      tolerations:
      {{- toYaml .Values.sbomCollector.daemonSetTolerations | nindent 8 }}
      serviceAccountName: {{ include "sbom-collector.serviceAccountName" . }}
      {{- with .Values.sbomCollector.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: sbom-collector
          securityContext:
            {{- toYaml .Values.sbomCollector.securityContext | nindent 12 }}
          image: "{{ .Values.sbomCollector.image.repository }}:{{ .Values.sbomCollector.image.tag }}"
          imagePullPolicy: {{ .Values.sbomCollector.image.pullPolicy }}
          args: [ "-health-probe-bind-address=:{{ .Values.healthCheck.port }}" ]
          env:
            - name: AGENT_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: AGENT_URL
              value: http://{{ include "kubernetes-agent.fullname" . }}:{{ .Values.agent.service.port }}
            - name: GOMEMLIMIT
              value: "{{ include "kubernetes-sbom-collector.goMemLimit" . }}"
            - name: SECRETS_ACCESS_ENABLED
              value: "{{ .Values.sbomCollector.secretsAccess.enabled }}"
            - name: RUN_COLLECTOR_AS_DAEMONSET
              value: "true"
            - name: SUPPRESS_ERROR_LOGS
              value: "{{ .Values.sbomCollector.logging.suppressErrors }}"
            {{- if and .Values.config.proxy .Values.config.proxy.httpProxy }}
            - name: HTTP_PROXY
              value: {{ .Values.config.proxy.httpProxy | quote }}
            {{- end }}
            {{- if and .Values.config.proxy .Values.config.proxy.httpsProxy }}
            - name: HTTPS_PROXY
              value: {{ .Values.config.proxy.httpsProxy | quote }}
            {{- end }}
            {{- if and .Values.config.proxy .Values.config.proxy.noProxy }}
            - name: NO_PROXY
              value: {{ .Values.config.proxy.noProxy | quote }}
            {{- end }}
          ports:
            - name: health
              containerPort: {{ .Values.healthCheck.port }}
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 90
            httpGet:
              path: /healthz
              port: health
          readinessProbe:
            initialDelaySeconds: 90
            httpGet:
              path: /readyz
              port: health
          resources:
            {{- toYaml .Values.sbomCollector.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /tmp
              name: tmp
            - mountPath: /.ecr
              name: ecr-cache-config
            - name: docker-sock
              mountPath: /var/run/docker.sock
              readOnly: true
            - name: containerd-sock
              mountPath: /run/containerd/containerd.sock
              readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
        - name: tmp
          emptyDir: { }
        - name: ecr-cache-config
          emptyDir: { }
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
        - name: containerd-sock
          hostPath:
            path: /run/containerd/containerd.sock
{{- end }}
