{{- if and .Values.sbomCollector.enabled .Values.sbomCollector.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sbom-collector.serviceAccountName" . }}
  labels:
    {{- include "sbom-collector.labels" . | nindent 4 }}
  {{- with .Values.sbomCollector.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- with .Values.sbomCollector.serviceAccount.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
