apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubernetes-agent.fullname" . }}
  labels:
    {{- include "kubernetes-agent.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "kubernetes-agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- if .Values.podAnnotations }}
        {{- toYaml .Values.podAnnotations | nindent 8 }}
        {{- end }}
      labels:
        aikido-security: kubernetes-agent
        {{- include "kubernetes-agent.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kubernetes-agent.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.agent.image.repository }}:{{ .Values.agent.image.tag }}"
          imagePullPolicy: {{ .Values.agent.image.pullPolicy }}
          args: ["-health-probe-bind-address=:{{ .Values.healthCheck.port }}"]
          env:
            - name: AGENT_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: GOMEMLIMIT
              value: "{{ include "kubernetes-agent.goMemLimit" . }}"
            {{- if and .Values.config.proxy .Values.config.proxy.httpProxy }}
            - name: HTTP_PROXY
              value: {{ .Values.config.proxy.httpProxy | quote }}
            {{- end }}
            {{- if and .Values.config.proxy .Values.config.proxy.httpsProxy }}
            - name: HTTPS_PROXY
              value: {{ .Values.config.proxy.httpsProxy | quote }}
            {{- end }}
            {{- if and .Values.config.proxy .Values.config.proxy.noProxy }}
            - name: NO_PROXY
              value: {{ .Values.config.proxy.noProxy | quote }}
            {{- end }}
          ports:
            - name: health
              containerPort: {{ .Values.healthCheck.port }}
              protocol: TCP
            - containerPort: 81
              name: api-port
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: health
          readinessProbe:
            httpGet:
              path: /readyz
              port: health
          resources:
            {{- toYaml .Values.agent.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: "/etc/kubernetes-agent"
              readOnly: true
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          secret:
            secretName: {{ include "kubernetes-agent.fullname" . }}
