{{- if not .Values.config.existingSecret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubernetes-agent.fullname" . }}
  labels:
    {{- include "kubernetes-agent.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  config.yaml: |
    apiEndpoint: {{ .Values.config.apiEndpoint | quote }}
    apiToken: {{ .Values.config.apiToken | quote }}
    controllerCacheSyncTimeout: {{ .Values.config.controllerCacheSyncTimeout | quote }}
    isSBOMCollectionEnabled: {{ .Values.config.isSBOMCollectionEnabled }}
{{- else }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubernetes-agent.fullname" . }}-config
  labels:
    {{- include "kubernetes-agent.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  config.yaml: |
    apiEndpoint: {{ .Values.config.apiEndpoint | quote }}
    apiTokenFile: "/etc/kubernetes-agent/token/apiToken"
    controllerCacheSyncTimeout: {{ .Values.config.controllerCacheSyncTimeout | quote }}
    isSBOMCollectionEnabled: {{ .Values.config.isSBOMCollectionEnabled }}
{{- end }}
