apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubernetes-agent.fullname" . }}
  labels:
    {{- include "kubernetes-agent.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  config.yaml: |
    apiEndpoint: {{ .Values.config.apiEndpoint | quote }}
    apiToken: {{ .Values.config.apiToken | quote }}
    controllerCacheSyncTimeout: {{ .Values.config.controllerCacheSyncTimeout | quote }}
