apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubernetes-agent.fullname" . }}
  labels:
    {{- include "kubernetes-agent.labels" . | nindent 4 }}
spec:
  selector:
    aikido-security: kubernetes-agent
  ports:
  - name: api-agent-port
    protocol: TCP
    port: 81
    targetPort: api-port
