{{- if .Values.runtimeProtection.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubernetes-agent-runtime-protection
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubernetes-agent.labels" . | nindent 4 }}
data:
  http-output.yaml: |
    http_output:
      enabled: true
      url: {{ include "runtimeProtection.httpOutputUrl" . | quote }}
  rules-override.yaml: ""
{{- end }}
