{{- if eq .Values.networkPolicy.enabled true }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "kubernetes-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      aikido-security: kubernetes-agent
  policyTypes:
    - Ingress
    {{- if .Values.networkPolicy.egress.enabled }}
    - Egress
    {{- end }}
  ingress:
    - from:
        - podSelector:
            matchLabels:
              aikido-security: kubernetes-sbom-collector
      ports:
        - protocol: TCP
          port: {{ .Values.agent.service.port }}
    - from:
        - podSelector: { }
        - namespaceSelector: { }
      ports:
        - protocol: TCP
          port: {{ .Values.agent.service.metricsPort }}
    {{- if .Values.runtimeDetection.enabled }}
    - from:
        - podSelector:
            matchLabels:
              aikido-security: kubernetes-agent-runtime-detection
      ports:
        - protocol: TCP
          port: {{ .Values.runtimeDetection.port }}
    {{- end }}
  {{- if .Values.networkPolicy.egress.enabled }}
  {{- if or .Values.networkPolicy.egress.rules .Values.networkPolicy.egress.extra }}
  egress:
    {{- range .Values.networkPolicy.egress.rules }}
    {{- toYaml (list .) | nindent 4 }}
    {{- end }}
    {{- range .Values.networkPolicy.egress.extra }}
    {{- toYaml (list .) | nindent 4 }}
    {{- end }}
  {{- else }}
  egress: []
  {{- end }}
  {{- end }}
{{- end }}
