name: Test

on:
  pull_request:
    paths:
      - 'kubernetes-agent/**'

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Install helm-unittest plugin
        run: helm plugin install https://github.com/helm-unittest/helm-unittest/releases/download/v1.1.1/unittest-1.1.1.tgz

      - name: Update chart dependencies
        run: helm dependency update kubernetes-agent

      - name: Run unit tests
        run: helm unittest kubernetes-agent
